name: dwaynerice
favicon: null
layout_spectrum: 0.24828
typography_spectrum: 0.37812
title: Dwayne Rice
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13467e'
    - '#c3cdd8'
    - '#a5afba'
    - '#4579a5'
    - '#5f92b8'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
