name: dwaynerice
favicon: null
layout_spectrum: 0.50187
typography_spectrum: 0.48686
title: Dwayne Rice
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13467e'
    - '#c3cdd8'
    - '#a5afba'
    - '#4579a5'
    - '#5f92b8'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
