name: dwaynerice
favicon: null
layout_spectrum: 0.37116666324436665
typography_spectrum: 0.1358116865158081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6342267044819891
  lightness: 0.9574047075584531
  saturation: 0.050697332015261054
  rhythmicContrast: 0.1986502418294549
purpose: []
