name: dwaynerice
favicon: null
layout_spectrum: 0.24828
typography_spectrum: 0.37812
title: Dwayne Rice
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecedef'
    - '#181e2e'
    - '#b8b8b6'
    - '#5a6793'
    - '#55372c'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
